### ISSUE TITLE
File import crashes on Android 7.x due to file: scheme being used

### ISSUE THREAD

**Issue by mendhak** [mendhak/gpsvisualizer#13]
https://commonsware.com/blog/2016/03/14/psa-file-scheme-ban-n-developer-preview.html

    android.os.FileUriExposedException: file:///storage/emulated/0/gpslogger/xxxxxxx.gpx exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:845)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8941)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:8926)
	at android.app.Activity.finish(Activity.java:5205)
	at android.app.Activity.finish(Activity.java:5225)
	at com.nononsenseapps.filepicker.AbstractFilePickerActivity.onFilesPicked(AbstractFilePickerActivity.java:161)
	at com.nononsenseapps.filepicker.AbstractFilePickerFragment.onClickOk(AbstractFilePickerFragment.java:215)
	at com.nononsenseapps.filepicker.AbstractFilePickerFragment$2.onClick(AbstractFilePickerFragment.java:170)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Looks like it is fixed here:

https://github.com/spacecowboy/NoNonsense-FilePicker/releases/tag/4.0.0-beta1

Requires updating

**Comment by mendhak** [comment]
Pushed to market should show up for you in a few hours
